name: rust

# trigger for all PRs and changes to master
on:
  push:
    branches:
      - master
      - port-ci-to-github-actions # during testing
  pull_request:

jobs:
  x86_64-unknown-linux-android-SSE2:
    name: "x86_64-unknown-linux-android + SSE2"
    uses: ./.github/workflows/build-test-verify.yml
    with:
      target: x86_64-linux-android
  i586-unknown-linux-gnu:
    uses: ./.github/workflows/build-test-verify.yml
    with:
      target: i586-unknown-linux-gnu
  x86_64-unknown-linux-gnu-SSE4_2:
    name: "x86_64-unknown-linux-gnu + SSE4.2"
    uses: ./.github/workflows/build-test-verify.yml
    with:
      target: x86_64-unknown-linux-gnu
      rustflags: "-C target-feature=+sse4.2"
